# -*- coding: utf-8 -*-
"""Calculo de metrica de avaliacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHSlrxo4Puq70S5cqIgyc7RfGpAAeV6J
"""

def calcular_metricas(VP, VN, FP, FN):
    # Acurácia
    acuracia = (VP + VN) / (VP + FN + FP + VN)

    # Sensibilidade (Recall)
    sensibilidade = VP / (VP + FN)

    # Especificidade
    especificidade = VN / (VN + FP)

    # Precisão
    precisao = VP / (VP + FP)

    # F-Score
    f_score = 2 * (precisao * sensibilidade) / (precisao + sensibilidade)

    return acuracia, sensibilidade, especificidade, precisao, f_score

# Exemplo de valores para VP, VN, FP e FN
VP = 50  # Verdadeiros Positivos
VN = 30  # Verdadeiros Negativos
FP = 10  # Falsos Positivos
FN = 5   # Falsos Negativos

acuracia, sensibilidade, especificidade, precisao, f_score = calcular_metricas(VP, VN, FP, FN)

print(f"Acurácia: {acuracia:.2f}")
print(f"Sensibilidade: {sensibilidade:.2f}")
print(f"Especificidade: {especificidade:.2f}")
print(f"Precisão: {precisao:.2f}")
print(f"F-Score: {f_score:.2f}")